name: build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build openssl 1.1.1n
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg ../vcpkg
        call ..\vcpkg\bootstrap-vcpkg.bat
        echo '{ "name": "dbkg", "version-string": "1.0.0", "dependencies": [ "openssl" ], "builtin-baseline": "2ac61f87f69f0484b8044f95ab274038fbaf7bdd", "overrides": [ { "name": "openssl", "version-string": "1.1.1" } ] }' > vcpkg.json
        ..\vcpkg\vcpkg install
        ..\vcpkg\vcpkg integrate install

    - name: Generating Makefiles
      shell: cmd
      run: |
        @set PERL=c:/Strawberry/perl/bin/perl
        c:/Strawberry/perl/bin/perl makelib.pl --perlpath=c:/Strawberry/perl/bin --busybox=./win32/busybox --wget=./win32/wget vc2022

    - name: Compiling
      shell: cmd
      run: |
        @set PERL=c:/Strawberry/perl/bin/perl
        .\win32\gmake-42 release

    - name: Package
      uses: actions/upload-artifact@v2
      with:
        name: package-win32
        path: ./bin.vs170/release/*
