name: build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - uses: msys2/setup-msys2@v2
      with:
        release: false
        update: true
        install: >-
          bison

    - name: Windows, generating Makefiles
      shell: cmd
      run: |
        @set PERL=c:/Strawberry/perl/bin/perl
        c:/Strawberry/perl/bin/perl makelib.pl --perlpath=c:/Strawberry/perl/bin --busybox=./win32/busybox --wget=./win32/wget --bison=c:/msys64/usr/bin/bison --flex=./bin/flex --verbose vc2022

    - name: Windows, compiling
      shell: cmd
      run: |
        @set PERL=c:/Strawberry/perl/bin/perl
        .\win32\gmake-42 release contrib
        .\win32\gmake-42 release

    - name: Windows, package
      uses: actions/upload-artifact@v2
      with:
        name: package-win32
        path: ./bin.vs170/debug/*
